spring:
  application:
    name: kafka-sample
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      properties:
        isolation.level: read_committed
    producer:
      bootstrap-servers: localhost:9092
      transaction-id-prefix: kafka-template-tx.
